// Centralized pool of traits
const TRAITS_POOL = [
  "Loves coding",
  "Has visited 3+ countries",
  "Plays a musical instrument",
  "Speaks 2+ languages",
  "Prefers tea over coffee",
  "Owns a pet",
  "Has run a marathon",
  "Is a morning person",
  "Enjoys video games",
  "Knows how to swim",
  "Can bake cookies from scratch",
  "Is afraid of heights",
  "Has tried skydiving",
  "Likes pineapple on pizza",
  "Can solve a Rubik's Cube",
  "Is left-handed",
  "Has been scuba diving",
  "Absolutely hates Durians",
  "Knows how to knit or crochet",
  "Has been on TV",
  "Has broken a bone",
  "Loves hiking",
  "Is a twin or has twins in the family",
  "Can juggle",
  "Speaks 3+ languages",
  "Enjoys gardening",
  "Has climbed a mountain",
  "Can whistle a tune",
  "Loves horror movies",
  "Has a tattoo",
  "Can touch their toes without bending knees",
  "Plays chess",
  "Loves board games",
  "Has attended a concert",
  "Knows sign language",
  "Has written a poem",
  "Is a great storyteller",
  "Knows how to sew",
  "Enjoys photography",
  "Has dyed their hair a bright color",
  "Has met a celebrity",
  "Can do impressions",
  "Has run a 5K race",
  "Has baked bread from scratch",
  "Has stayed awake for 24+ hours",
  "Can do a handstand",
  "Has been camping",
  "Knows martial arts",
  "Has been to a theme park",
  "Can name all the GRCs in Singapore",
  "Has lived in more than 3 cities",
  "Enjoys painting or drawing",
  "Is a cat person",
  "Is a dog person",
  "Has ridden a horse",
  "Can play poker",
  "Knows how to surf",
  "Is good at trivia",
  "Can bake a cake",
  "Has performed on stage",
  "Can recite a movie quote perfectly",
  "Loves romantic comedies",
  "Has been on a road trip",
  "Not born in Singapore",
  "Has volunteered for a charity",
  "Has worked in customer service",
  "Has taken a dance class",
  "Knows how to play darts",
  "Can make origami",
  "Is always early",
  "Has written a book or short story",
  "Loves the beach",
  "Can do magic tricks",
  "Has visited a famous landmark",
  "Loves classic rock music",
  "Has made a YouTube video",
  "Has played in an orchestra",
  "Can name all the planets in order",
  "Has worked in a restaurant",
  "Knows a lot about history",
  "Is a fan of sci-fi movies",
  "Has played a team sport",
  "Has ridden in a hot air balloon",
  "Enjoys stargazing",
  "Knows how to play pool",
  "Has never broken a bone",
  "Is a fan of anime",
  "Can recite π to 10+ digits",
  "Can tie a cherry stem with their tongue",
  "Can do the splits"
];

  
  module.exports = TRAITS_POOL;
  