// Centralized pool of traits
const TRAITS_POOL = [
  "Loves coding",
  "Has visited 3+ countries",
  "Plays a musical instrument",
  "Speaks 2+ languages",
  "Prefers tea over coffee",
  "Owns a pet",
  "Has run a marathon",
  "Is a morning person",
  "Enjoys video games",
  "Knows how to swim",
  "Can cook a signature dish",
  "Has a hidden talent",
  "Is afraid of heights",
  "Has tried skydiving",
  "Likes pineapple on pizza",
  "Can solve a Rubik's Cube",
  "Has read 50+ books in a year",
  "Is left-handed",
  "Has been scuba diving",
  "Loves spicy food",
  "Knows how to knit or crochet",
  "Has been on TV",
  "Owns a collection of something",
  "Has broken a bone",
  "Loves hiking",
  "Is a twin or has twins in the family",
  "Can juggle",
  "Speaks 3+ languages",
  "Has won a competition",
  "Enjoys gardening",
  "Has climbed a mountain",
  "Can whistle a tune",
  "Loves horror movies",
  "Has a tattoo",
  "Can touch their toes without bending knees",
  "Plays chess",
  "Loves board games",
  "Has attended a concert",
  "Knows sign language",
  "Has written a poem",
  "Is a great storyteller",
  "Knows how to sew",
  "Enjoys photography",
  "Has dyed their hair a bright color",
  "Has met a celebrity",
  "Can do impressions",
  "Has run a 5K race",
  "Loves sushi",
  "Has baked bread from scratch",
  "Has stayed awake for 24+ hours",
  "Can do a handstand",
  "Has been camping",
  "Knows martial arts",
  "Has been to a theme park",
  "Can name all 50 U.S. states",
  "Has lived in more than 3 cities",
  "Enjoys painting or drawing",
  "Is a cat person",
  "Is a dog person",
  "Has ridden a horse",
  "Can play poker",
  "Knows how to surf",
  "Is good at trivia",
  "Can bake a cake",
  "Has performed on stage",
  "Can recite a movie quote perfectly",
  "Has built something with wood",
  "Loves romantic comedies",
  "Has been on a road trip",
  "Is afraid of spiders",
  "Has volunteered for a charity",
  "Has worked in customer service",
  "Has taken a dance class",
  "Knows how to play darts",
  "Can make origami",
  "Is always early",
  "Has written a book or short story",
  "Loves the beach",
  "Can do magic tricks",
  "Has visited a famous landmark",
  "Loves classic rock music",
  "Has made a YouTube video",
  "Knows how to play an unusual instrument",
  "Has tried a food challenge",
  "Is good at math",
  "Can name all the planets in order",
  "Has worked in a restaurant",
  "Knows a lot about history",
  "Can name 10 types of animals",
  "Is a fan of sci-fi movies",
  "Has played a team sport",
  "Is good at public speaking",
  "Loves mystery novels",
  "Has tried a unique hobby",
  "Has ridden in a hot air balloon",
  "Enjoys stargazing",
  "Has attended a music festival",
  "Knows how to play pool",
  "Has never broken a bone",
  "Is a fan of anime",
  "Has been to a zoo or aquarium"
];

  
  module.exports = TRAITS_POOL;
  